name: CI

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
  push:
    branches: [develop, main]

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    uses: FourIQ/development/.github/workflows/ci-reusable.yml@main
    secrets: inherit
    with:
      repo: redis-time-series
